### ISSUE TITLE
GetConsoleMode error

### ISSUE THREAD

**Issue by ccheraa** [CircleCI-Public/windows-orb#25]
The currently installed version of OpenSSH has this issue PowerShell/Win32-OpenSSH#856 which has been fixed in [version 8](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.0.0.0p1-Beta).
I think this version or a newer one should be preinstalled.

**Comment by mrothstein74** [comment]
@ccheraa i can include this in the nest 'edge' image a create later this month if needed. Did you try this with the latest windows orb 5.0.0? This orb has Windows Sever 2022 as the default. Please let me know if you still see this issue there.

**Comment by felicianotech** [comment]
Just checked. Windows Server 2022 images, at least recent ones, definitely include OpenSSH v8.
