### ISSUE TITLE
An issue with backslash escapes and bash.exe

### ISSUE THREAD

**Issue by mkarp** [CircleCI-Public/windows-orb#26]
Hey there!

Using the latest version of the windows-orb: `circleci/windows@2.4.1`

I'm using https://github.com/CircleCI-Public/slack-orb on a CircleCI Windows VM with `shell: bash.exe`. In this Orb, there's a `sed 's/\\/\\\\/g'` command, which runs as expected on Mac and Docker VMs but fails on a Windows VM. It seems that the backslashes are escaped prematurely, and the command is interpreted as `sed 's/\/\\/g'`.

You can read more about the issue here: https://github.com/CircleCI-Public/slack-orb/issues/217#issuecomment-987060538

**Comment by mkarp** [comment]
I've created a minimal repro to illustrate the issue https://github.com/mkarp/circleci-win-bash

**Comment by felicianotech** [comment]
Apologies for the delay. The CircleCI Slack orb does not support Windows: https://github.com/CircleCI-Public/slack-orb/wiki/FAQ

**Comment by mkarp** [comment]
@felicianotech Thank you for getting back to the issue! I understand that the slack-orb does not support Windows, but I've mentioned it as an example that reveals the issue. Please see https://github.com/mkarp/circleci-win-bash for a minimal reproduction of the issue. In short, backslashes are escaped incorrectly in inline bash commands when running within Windows workers. On Docker/Linux/Mac workers the behaviour is correct.
