### ISSUE TITLE
Update to .net 6 and VS 2022

### ISSUE THREAD

**Issue by Fischchen** [CircleCI-Public/windows-orb#27]
Now that VS 2022 is not in beta anymore, as well as .net 6 being in LTS, it would make sense so update to that.

**Comment by mrothstein74** [comment]
windows orb now supports .net 6 and vs 2022 in version 4.0

version: 2.1
  orbs:
    win: circleci/windows@4.0
  jobs:
    build:
      executor: win/server-2022
      steps:
        - run: Write-Host 'Hello, Windows'
  workflows:
    my-workflow:
      jobs:
        - build
