### ISSUE TITLE
Migrate to Orb Tools v11

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/windows-orb#28]
Migrate to Orb Tools v11.1
https://github.com/CircleCI-Public/orb-tools-orb/blob/master/MIGRATION.md

**Comment by felicianotech** [comment]
I think Henna is taking this.

**Comment by HennaAbbas** [comment]
@felicianotech @KyleTryon Can I please have permissions to enable dynamic config, create a branch etc.

**Comment by KyleTryon** [comment]
> @felicianotech @KyleTryon Can I please have permissions to enable dynamic config, create a branch etc.

Dynamic configuration is enabled now, but should not be required for a PR. Rather than us providing write permissions to the repo, please instead open a pull request from a fork.

**Comment by felicianotech** [comment]
Was completed in #35.
