### ISSUE TITLE
Readme is bad

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/windows-orb#36]
- The title is from the template
- it has publishing instructions from before Orb Tools v11
- check for other issues

**Comment by felicianotech** [comment]
Should be done this week.

**Comment by mrothstein74** [comment]
readme has been updated

https://github.com/CircleCI-Public/windows-orb/pull/41

**Comment by mrothstein74** [comment]
@felicianotech please review and close if it looks ok to you

**Comment by EricRibeiro** [comment]
Closed in #36.
