### ISSUE TITLE
Changelog & Package information

### ISSUE THREAD

**Issue by Kruptein** [CircleCI-Public/windows-orb#37]
I've been using version 2.4.0 for a while now with great success.

I however recently stumbled upon an issue with using something in python that is not available on the python version that is installed by default on the orb, so I wanted to look into which python version is installed with the 2.4 orb, but I've been unable to find this information easily in any of the official docs.

The orb registry mentions "An executor preloaded with Visual Studio 2019 plus a number of other development tools.", which doesn't say a lot. Is this supposed to be a "try it out to find out" or am I missing an obvious piece of documentation somewhere.

In a similar vein I noticed that the orb now has version 4.1.1 but haven't been able to figure out what has changed in all these releases as there is no changelog in this repository or on the orb registry page, nor is there information in the release section on GitHub.

**Comment by ahirner** [comment]
Example: miniconda `4.6.14` was silently removed from orb version `4.1.1` to `5.0.0`.
