### ISSUE TITLE
Support for .NET 7

### ISSUE THREAD

**Issue by basdijkstra** [CircleCI-Public/windows-orb#43]
I'm building a library I'm developing with your Windows orb, and since I'd like to target .NET 7 next to .NET 6 and .NET Core 3.1 (both of which work fine), could you tell me if and when you're planning to include .NET 7 in this orb?

**Comment by BytesGuy** [comment]
@basdijkstra Hi, we do plan to include .Net 7 and are beginning to test this in the images, however we do not currently have an ETA. Our goal is to have this installed side by side with .Net 6, but at the moment this appears to be problematic. For now I will add the backlog label to this issue and we will update you once this is ready. (see also[ this discuss post](https://discuss.circleci.com/t/plans-for-supporting-recent-net-sdks/46873))

**Comment by basdijkstra** [comment]
Thanks @BytesGuy for the update. For this particular repository and pipeline I’ve moved to GitHub Actions (not what you want to hear, I know), but I’m sure a pipeline supporting .NET 7 in CircleCI will be useful to me in the future.

**Comment by BytesGuy** [comment]
@basdijkstra The latest image should actually be supporting .NET 7, can you give this a try?

```
#!powershell.exe -ExecutionPolicy Bypass
dotnet --list-sdks
6.0.406 [C:\Program Files\dotnet\sdk]
7.0.201 [C:\Program Files\dotnet\sdk]
```

We are not actually specifying this anywhere in the build, but it is probably a byproduct of another install. We will be using Chocolatey to try and install .NET 6 and 7 side by side from the next release if all goes well.

**Comment by BytesGuy** [comment]
I am closing this issue out as we not explicitly install .Net 7 in the Windows 2022 images moving forward. Please reach out to [support](https://support.circleci.com/hc/en-us) if you face any issues with this. Thanks!
