### ISSUE TITLE
bug: path issue using choco with 2022 server

### ISSUE THREAD

**Issue by tony-go** [CircleCI-Public/windows-orb#45]
Hi 👋🏼 

Thanks for this super handy orb :) 

## The issue

I just realized that:

**Given**: version `4.1.1` with the `win/server-2022` executor
**Or**: version `5.0.0` with the default executor

**When**: I use chocolatey to install a dependency (for example `CMake`)

**Then**: I got an error: `cmake : The term 'cmake' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.`

It seems that the path is not appropriately set. It works with version `4.1.1` and the default executor (`win/default`). So it's what I currently use but then I cannot use version 2022 of the visual studio as the embedded one is 2019.

## Explored solutions

I have tried to do two things so far:
- Try to set the path manually
- Try another way of installing it, like `curl` or even `Invoke-WebRequest`

Let me know if you need more questions ^^

Cheers 🙌🏼

**Comment by BytesGuy** [comment]
@tony-go Hi thanks for this bug report. Please can you open a ticket with CircleCI support (if this is still an issue) as this sounds like more of an issue with the image itself rather than the Orb and would require further investigation. Thanks!
