### ISSUE TITLE
Commands are operating on various circleci, circleci_packer, and circleci.PACKER-<hex> user directories since upgrading to 5.0.0

### ISSUE THREAD

**Issue by jedwards1211** [CircleCI-Public/windows-orb#50]
I upgraded from the orb version 2.2.0 to 5.0.0 today and programs I install in one command aren't available in another.

Here's the relevant part of my config:

```
  build-windows:
    executor: win/default 
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: Start-Process powershell -Wait -Verb runAs -ArgumentList "iwr https://get.pnpm.io/install.ps1 -useb | iex"
      - run:
          name: Install WiX
          command: |
            choco install wixtoolset --version 3.11.2
            refreshenv
      - run:
          name: Install dependencies
          command: |
            export PNPM_HOME="/c/Users/circleci/AppData/Local/pnpm"
            export PATH="$PNPM_HOME:/c/Program Files (x86)/WiX Toolset v3.11/bin:$PATH"
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
            pnpm env use --global << pipeline.parameters.node-version >>
            pnpm i -g node-gyp
            pnpm i --frozen-lockfile
          shell: bash.exe
```

With the `win: circleci/windows@2.2.0` orb this worked.  With version 5.0.0 of the orb , it can't find `pnpm`.  When I SSHed into PowerShell I saw that it was now installing pnpm under the `C:\Users\circleci.PACKER-633B1A5A` directory.  Listing `C:\Users` showed three different user directories:

```
PS C:\Users\circleci.PACKER-633B1A5A> dir C:\Users


    Directory: C:\Users


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         10/3/2022   7:09 PM                circleci
d-----          3/8/2023   7:41 PM                circleci.PACKER-633B1A5A
d-----         10/3/2022   6:46 PM                circleci_packer
```

The docs don't seem to mention anything about this, is there any good reason for it?

**Comment by montella1507** [comment]
This is really huge problem and breaking change...  it is really difficult to use tilde in various commands...

**Comment by BytesGuy** [comment]
Hi, please open a support ticket with CircleCI support as this is an issue with the image rather than the Orb itself. 

V5 of the Orb moved the default Windows version to 2022: https://github.com/CircleCI-Public/windows-orb/releases/tag/v5.0.0 

Server 2022 builds were moved to a Packer and Ansible based build system, so this looks like an artefact of this change.
